### ISSUE TITLE
differentiable supervoxels

### ISSUE THREAD

**Issue by jakubMitura14** [ozencgungor/CMB_Topology_ML_JAX#1]
Hello thank you for sharing your very interesting repository publically. I see You are using superpixels in your algorithms is generation of superpixels differentiable in your implementation? I mean given process array->supervoxel->loss you van run backpropagation from loss to array?

Thank you !

**Comment by ozencgungor** [comment]
Hi @jakubMitura14. 

The code in this repo is for working with images on the surface of a sphere represented through graphs, but I think the idea is applicable to 3D images with supervoxels.

If I understand your question right: superpixels are "generated" either through convolutions or simple pooling and the process should be differentiable, since the generated superpixels depend on the trainable parameters of the convolution kernel. Currently, the layers that implement processes that end up generating superpixels through convolutions are only implemented for the HEALPix pixellization scheme but it could be implemented for other hierarchical pixellization schemes.

Hope this answers your question.

**Comment by jakubMitura14** [comment]
Thank you !!
